### ISSUE TITLE
feature request: global save

### ISSUE THREAD

**Issue by idelice** [oysandvik94/curl.nvim#14]
It would add so much value and save time, if the request that the user makes, is saved globally i.e. when you switch over to another nvim instance to do some work and toggle this plugin - you would be able to see the request you've made from the  previous instance.

**Comment by oysandvik94** [comment]
Should be doable! 

I'm thinking maybe adding a parameter to CurlOpen, such as

':CurlOpen global'

Then you can decide whether to open a global scratch that persists across all sessions, or one local to your current directory.

And of course corresponding lua functions.

I can also try and hook in to neovim sesison functionality. I'm not super familiar with it, but then it might work with more peoples workflows.

Would this work for your use case?

**Comment by idelice** [comment]
I would say git gitpad.nvim is doing a great job saving sessions depending on the use case. Maybe we could do the same here?

**Comment by oysandvik94** [comment]
I'll check it out!

**Comment by oysandvik94** [comment]
The global and custom buffers are merged to main now, check out https://github.com/oysandvik94/curl.nvim?tab=readme-ov-file#-persistence
