### ISSUE TITLE
[Feature Request]: Other options from curl like "--resolve"

### ISSUE THREAD

**Issue by bertverbessem** [oysandvik94/curl.nvim#19]
Since this is called "curl", could it be possible to have a collection of commands that are outside of the normal scope?

For example:

```
URL=some_url
PORT=443
IP=some_ip

curl https://"$URL" --resolve "$URL":"$PORT":"$IP"
```

At the moment it says: curl: (49) Couldn't parse CURLOPT_RESOLVE entry '::'

**Comment by oysandvik94** [comment]
Hi, I saw you closed this issue, but wanted to mention that I do want to do something like this, so you can define variables in the file instead. However, environment variables should work, so if you have set some global ones then they should work with curl.nvim. I am not sure if it reads from your current shell session (maybe), but I can also try and make that work.

**Comment by oysandvik94** [comment]
Right, so variables are scoped to the the file itself. Immidately thinking of maybe a metadata field, like in markdown/obsidian, at the top which is seperated by i.e. ---
Then you could also specify hostname.
Would make it closer to HTTP specs maybe like in jetbrains, but still compatible with curl flags. 

Thanks for using the plugin and providing feedback!

**Comment by oysandvik94** [comment]
Also realizing I should have an option to scope custom buffers, so you can have a set of curl command files for each project.

**Comment by oysandvik94** [comment]
@bertverbessem Awesome, thanks! I will draw some inspiration from that when I get to #12
