### ISSUE TITLE
bug: custom created curls not working anymore instead they are one *single* curl

### ISSUE THREAD

**Issue by idelice** [oysandvik94/curl.nvim#31]
### How to reproduce

1. `CurlOpen custom a`
2. Do your thing..
3. Close the plugin
4. `CurlOpen custom b`
5. Now you see the curl you did in step 1

### Expectation
custom *a* and *b* should *not* be merged into a single curl

**Comment by oysandvik94** [comment]
Strange, I'll check this out tonight!

Meanwhile, I recommend switching to 

:CurlOpen collection global {any_name}
:CurlOpen collection scoped {any_name}

The "custom" option is deprecated. There should hopefully be a notification when using it.

There are also equivalent lua methods that you can find in the docs.

The "collection global" should be equivalen to "custom", and "collection scoped" is new and scopes custom commands to your working directory.

**Comment by oysandvik94** [comment]
@idelice My bad, I had only deprecated the lua command, not the user command. See #20
