### ISSUE TITLE
The buffer created by CurlOpen cannot be found by CurlCollection

### ISSUE THREAD

**Issue by name-jerry** [oysandvik94/curl.nvim#35]
![CurlOpen](https://github.com/user-attachments/assets/698bc766-9b53-47de-b07b-4967eefac2c7)
![CurlCollection scoped](https://github.com/user-attachments/assets/e1844171-aa7c-4337-a847-84b665d0cf94)
I have opened a buffer in the workspace using 'CurlOpen', and I have confirmed that the data in this buffer is persisted, but this buffer still cannot be checked by CurlCollection scoped or global

**Comment by oysandvik94** [comment]
Sorry I missed this @name-jerry 
Could you explain a bit more?

Are you using CurlOpen collection in this case, or just CurlOpen?

**Comment by name-jerry** [comment]
> Sorry I missed this @name-jerry Could you explain a bit more?
> 
> Are you using CurlOpen collection in this case, or just CurlOpen?

now it right
