### ISSUE TITLE
Feature: open in split

### ISSUE THREAD

**Issue by swtch1** [oysandvik94/curl.nvim#37]
I love the simplicity of this project but I don't use tabs.  Would you consider adding a setting that opens this in a split instead of in a new tab?

**Comment by oysandvik94** [comment]
For sure, should not be too hard!

How do you imagine the split looking, considering the functionality as of now is having a split for commands, and a split of the output? Is having a triple vertically split window ok, or is there some other construction you would prefer?

Hope I can crack this out sooner or later, progress have been a bit slow on this plugin the last few weeks, mostly because I've just been a bit busy.

**Comment by swtch1** [comment]
Simple:
Just replace my current active buffer with the curl file.  This is similar to my current flow which is `:CurlOpen` > `:tabclose` > open the buffer which contains `.curl`.  From there it works as expected, when I curl the split opens.

Ideal State:
Open a full-width horizontal split like `:copen` with the curl buffer.  Then when I curl the vsplit opens.  This matches the model of a few other plugins so I think it makes sense.

Plugins like skywind3000/asyncrun.vim + skywind3000/vim-terminal-help (my must-have plugin) forces a full-width split and plugins like jeetsukumaran/vim-buffergator and hedyhli/outline.nvim force a full vertical split.

A bonus would be a `CurlToggle` command so I could open and close with the same keymap but that's a different feature entirely.

**Comment by oysandvik94** [comment]
@swtch1 Agree that toggle would be useful, I created an issue for it here #40 

I have a branch that you can try if you want that opens in split, to see if it works for you:

If you are using lazy:
```lua
{
	"oysandvik94/curl.nvim",
    branch = "open_in_split",
	dependencies = {
		"nvim-lua/plenary.nvim",
	},
	config = function()
		local curl = require("curl")
		curl.setup({
			open_with = "split",
		})
    end 
}
```

**Comment by swtch1** [comment]
Yeah, this is great.  The only piece that would make it better is if it forced a full horizontal split even when I have several buffers open, but this is a huge improvement for me.

Thanks so much for implementing this!

**Comment by oysandvik94** [comment]
Of course, that's what the full horizontal split means! Shouldn't be too hard to implement that as well, I was just blanking on the case where you already have splits in your buffer.

**Comment by oysandvik94** [comment]
@swtch1 Sorry, I completely forgot about this! But I fixed now so it opens in a full horizontal split, and it's now merged to main.

**Comment by swtch1** [comment]
I love it.  Starred the project, thank you.
