### ISSUE TITLE
Create seperate terminal app 

### ISSUE THREAD

**Issue by bertverbessem** [oysandvik94/curl.nvim#38]
HI,

I don't know if possible or if it's hard or not. Can this become an term-gui app like lazygit ?

Kr,

**Comment by oysandvik94** [comment]
It would take a whole rewrite, since it's written using Neovim api, and all the gui stuff is coupled with neovim.

It wouldn't be a massive job, but not in the scope of this plugin, and would then be a different thing entirely.
